config/routes.rb
Rails.application.routes.draw do
	root 'events#index'

	get    '/login',  to: 'sessions#new'
	post   '/login',  to: 'sessions#create'
	delete '/logout', to: 'sessions#delete'
	resources :users, only: [:new, :create, :show]
	resources :events, only: [:index, :new, :create, :show]
	post   '/attend', to: 'events#attend'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :creator, :class_name => "User"
	has_many :event_attendees, dependent: :destroy
	has_many  :attendees, :through => :event_attendees, source: :user
	validates :title, presence: true
	validates :date, presence: true
	validates :location, presence: true
	validates :description, presence: true

	scope :past, -> { where("date < ?", Date.today) }
	scope :upcoming, -> { where("date > ?", Date.today) }
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
	belongs_to :event
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :created_events, :foreign_key => "creator_id", :class_name => "Event"
	has_many :event_attendees
	has_many :attended_events, :through => :event_attendees, source: :event 
	validates :username, presence: true, uniqueness: true
	has_secure_password

	def upcoming_events
		attended_events.where("date > ?", Date.today)
	end

	def previous_events
		attended_events.where("date < ?", Date.today)
	end
end

app/controllers/application_controller.rb
include ApplicationHelper

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :logged_in, only: [:attend, :create]

	def index
		@events = Event.all
	end

	def show
		@event = Event.find_by(id: params[:id])
	end

	def new
		@event = Event.new
	end

	def create
		@user = current_user
		@event = @user.created_events.build(event_params)
		if @event.save
			@event.attendees << @user
			flash[:success] = "Event created"
			redirect_to @user
		else
			flash.now[:error] = "#{@event.errors.messages}"
			render 'new'
		end
	end

	def attend
		Event.find_by(id: params[:id]).attendees << current_user
		redirect_to current_user 
	end

	private

		def logged_in
			unless logged_in?
				flash[:error] = "Please login first"
				redirect_to login_url
			end
		end

		def event_params
			params.require(:event).permit(:title, :date, :location, :description)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		if @user = User.find_by(username: session_params[:username])
			session[:user_id] = @user.id
			redirect_to root_url
		else
			flash.now[:error] = "Please try again"
			render 'new'
		end
	end

	def delete
		reset_session
		redirect_to root_url
	end

	private

		def session_params
			params.require(:session).permit(:username, :password)
		end	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.create(user_params)
		if @user.save
			flash[:success] = "User created"
			session[:user_id] = @user.id
			redirect_to root_url
		else
			flash.now[:error] = "#{@user.errors.messages}"
			render 'new'
		end
	end

	def show
		@user = User.find_by(id: params[:id])
	end

	private

		def user_params
			params.require(:user).permit(:username, :password)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def logged_in?
  	!current_user.nil?
  end

  def current_user
  	@user = User.find_by(id: session[:user_id])
  end

  def current_user=(user)
  	@user = user
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
Past Events:<P>

<% Event.past.each do |e| %>
	<%= link_to e.title, e %>, created by <%= e.creator.username%> <p>
<% end %>

<p>Upcoming Events:<p>

<% Event.upcoming.each do |e| %>
	<%= link_to e.title, e %>, created by <%= e.creator.username%> <p>
<% end %>

app/views/events/new.html.erb
<%= form_for @event do |f| %>
	<%= f.label :title %>:<p>
	<%= f.text_field :title %><p>

	<%= f.label :date %>:<p>
	<%= f.date_field :date %><p>
	
	<%= f.label :location %>:<p>
	<%= f.text_field :location %><p>
	
	<%= f.label :description %>:<p>
	<%= f.text_area :description %><p>

	<%= f.submit "Create event" %>
<% end %>

app/views/events/show.html.erb
<%= button_to "Attend", attend_url(id: @event.id) %> <p> <%= @event.title %>, created by <%= @event.creator.username%> <p>

Date: <%= @event.date%><p>

Location: <%= @event.location%><p>

Description: <%= @event.description%><p>

Attendees: <p>

<% @event.attendees.each do |a| %>
	<%= a.username %> 
<% end %>

app/views/layouts/_header.html.erb
<%= link_to "All Events", events_url %> | 

<% if logged_in? %>
	Logged in as: <%= link_to @user.username, @user %> | 
	<%= link_to "Create event", new_event_url %> | 
	<%= link_to "Log out", logout_url, method: :delete %> 
<% else %>
	<%= link_to "Log in", login_url %> | 
	<%= link_to "Sign up", new_user_url %>
<% end %>
<p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
  	<% flash.each do |k, v| %>
  		<%= content_tag :div, v, class: "flash #{k}" %>
  	<% end %>
  	<p>
    <%= yield %>
  </body>
</html>

app/views/users/_user_events.html.erb
<p>Attended Events:<P>
<% @user.previous_events.each do |e| %>
	<%= link_to e.title, e %>, created by <%= e.creator.username %>
<% end %>
<p>Upcoming Events:<p>
<% @user.upcoming_events.each do |e| %>
	<%= link_to e.title, e %>, created by <%= e.creator.username %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
		<%= f.label :username %>
		<%= f.text_field :username %>

		<%= f.label :password %>
		<%= f.password_field :password %>

		<%= f.submit "Submit" %>
<% end %>

app/views/users/show.html.erb
Username: <%= @user.username %>
<p>
<%= render 'users/user_events' %>